# generated by datamodel-codegen:
#   filename:  item.schema.json
#   timestamp: 2025-07-03T14:59:52+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Item(BaseModel):
    name: str = Field(..., description="The item's name.")
    price: float = Field(..., description="The item's price.")
    is_offer: Optional[bool] = Field(None, description="Whether the item is on offer.")
